apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: load-generator
spec:
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: celerosolutions/kubernetesloadgeneratordemo:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 200Mi