apiVersion: v1
kind: Service
metadata:
  name: load-generator
  namespace: load-generator
spec:
  selector:
    app: load-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer